#!/bin/bash

set -eu

dspath="$1"
derivds=$(basename "$dspath")
ds=${derivds%-*}

fmriprep_version=$(cat "$dspath/dataset_description.json" | python3 -c "import sys,json; j=json.load(sys.stdin); print(next(x['Version'] for x in j['GeneratedBy'] if x['Name']=='fMRIPrep'))")

# Let's verify that all subjects have that version
fmriprep_versions=$(grep -h "fMRIPrep version:" $dspath/sub-*.html  |  sort | uniq | sed -e 's,.*: ,,' -e 's,<.*,,g')

if [ "$fmriprep_versions" != "$fmriprep_version" ]; then
	echo "ERROR: got mismatch between versions in .html files ($fmriprep_versions) and dataset_description.json ($fmriprep_version)"
	exit 1
fi

mkdir -p "$ds";

echo "I: producing software record"
cmdline=$(cat $dspath/.reproman/jobs/local/*/command-array | tr '\0' '\n'  | head -n 1  | sed -e "s,--participant-label '01',--participant-label 'SENSORED-TODO-MAKE-PER-SUBJECT',g" -e "s,sub-[0-9]\+,sub-SENSORED-TODO-MAKE-PER-SUBJECT,g")

cat >| "$ds/fmriprep-software-metadata.csv" << EOF
title,description,version,url,cmdline,platform,ID
fmriprep,fMRIPrep is a NiPreps (NeuroImaging PREProcessing toolS) application (www.nipreps.org) for the preprocessing of task-based and resting-state functional MRI (fMRI).,$fmriprep_version,https://fmriprep.org/en/stable/,$cmdline,GNU/Linux,https://scicrunch.org/resolver/RRID:SCR_016216
EOF

echo "I: producing .csv extract"
$(dirname $0)/SumarizeFmriprep/summarize_confounds "$dspath" "$ds/fmriprep-summarized-confounds.csv"

# TEMP: TODO -- make that summarize confounds add a proper column with source_url
# didn't work -- added newline symbol for some reason
#sed -i -e '1s/$/,source_url/' "$ds/fmriprep-summarized-confounds.csv"

echo "I: producing final ttl"
csv2nidm \
	 -csv_map code/SumarizeFmriprep/metadata/summarize_confounds_fmriprep_dictionary.csv \
	 -no_concepts \
	 -csv "$ds/fmriprep-summarized-confounds.csv" \
	 -derivative "$ds/fmriprep-software-metadata.csv" \
	 -out "$ds/fmriprep-summarized-confounds.ttl"

